name = "stm32f746disco"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Olivier Henley"]
maintainers = ["Olivier Henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]

[[depends-on]]
stm32_hal = "0.1.0-dev"
cortex_m = "0.5.0"
embedded_components = "0.2.0"

[[pins]]
stm32_hal = { url="https://github.com/GNAT-Academic-Program/stm32_hal.git", branch="stm32f7_usart" }

[configuration.values.cortex_m]
core = "m7f"

[configuration.values.stm32_hal]
device = "stm32f746"